# Generated by Django 5.2.4 on 2025-07-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ST', 'Student'), ('IN', 'Instructor')], default='ST', max_length=2),
        ),
    ]
