# Generated by Django 5.2.4 on 2025-07-23 13:16

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', validators=[courses.validators.validate_file_size]),
        ),
    ]
